# Generated by Django 3.1.3 on 2020-11-24 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usetr',
            new_name='User',
        ),
    ]
