# Generated by Django 3.1.3 on 2020-11-26 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_user_id_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id_admin',
            new_name='is_admin',
        ),
    ]
